### ISSUE TITLE
Error in deleting collection - error.call is not a function

### ISSUE THREAD

**Issue by pradeep-here** [samuk190/localbase#49]
Hi @dannyconnell, plz help check below error

localbase version 
> "localbase": "^0.7.5",

Code:
```
      let lbaseDb = new Localbase('my_db')  
      lbaseDb.collection('my_col').delete()
```

Error:
```
delete.js?fd25:64 Uncaught (in promise) TypeError: error.call is not a function
    at eval (delete.js?fd25:64)

eval	@	delete.js?fd25:64
Promise.catch (async)		
deleteNextCollectionFromQueue	@	delete.js?fd25:62
runDeleteCollectionQueue	@	delete.js?fd25:41
addToDeleteCollectionQueue	@	delete.js?fd25:35
deleteCollection	@	delete.js?fd25:76
eval	@	delete.js?fd25:176
deleteIt	@	delete.js?fd25:10
_callee6$	@	orgs.js?e6b2:1252
tryCatch	@	runtime.js?96cf:63
invoke	@	runtime.js?96cf:293
eval	@	runtime.js?96cf:118
asyncGeneratorStep	@	asyncToGenerator.js?1da1:3
_next	@	asyncToGenerator.js?1da1:25
eval	@	asyncToGenerator.js?1da1:32
eval	@	asyncToGenerator.js?1da1:21
```

**Comment by kaue42** [comment]
I'm also getting this error when i do 

`db.collection('example').delete()`

`Uncaught (in promise) TypeError: e.call is not a function
    deleteNextCollectionFromQueue https://unpkg.com/localbase/dist/localbase.min.js:1
    promise callback*[8]</n.default/</t.deleteCollection/t.deleteNextCollectionFromQueue https://unpkg.com/localbase/dist/localbase.min.js:1
    runDeleteCollectionQueue https://unpkg.com/localbase/dist/localbase.min.js:1
    addToDeleteCollectionQueue https://unpkg.com/localbase/dist/localbase.min.js:1
    deleteCollection https://unpkg.com/localbase/dist/localbase.min.js:1
    default https://unpkg.com/localbase/dist/localbase.min.js:1
    default https://unpkg.com/localbase/dist/localbase.min.js:1
    <anonymous> https://localhost/pwa/wp-content/themes/html/assets/js/localbase.js:21`

**Comment by samuk190** [comment]
Can you try new version?
