### ISSUE TITLE
Where

### ISSUE THREAD

**Issue by carlosasjr** [samuk190/localbase#79]
Is possible create this code?

 const products = await db.collection(`${ RESOURCE }`)
        .where("company_id", "==", company_id)
        .where("inactive", "==", 0)
        .orderBy("description")
        .get();

**Comment by Mashiane** [comment]
Hi, can you please provide an example of how to use this where filter? 

Thanks

**Comment by samuk190** [comment]
> Hi, can you please provide an example of how to use this where filter?
> 
> Thanks

  db.collection('users')
  .doc({id: 1}).get().then(user => {
    const u = user
   db.collection('orders')
      .get({keys: false, filter: {userId: u.id}}).then(orders => { 
       u.orders = orders
       console.log(u)
      })
  })
